### ISSUE TITLE
Safari < 11.0 doesn't load new GH screen

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#22]
Cannot load new Golden Hour screen. It seems to be an iOS issue.  iOS 11.0 is OK, iOS 10.0 and 9.3.4 is not OK.

Seen on:
 iPad Pro / 10.2   Mobile Safari 10.0  2732x2048 (Landscape)
https://app.crossbrowsertesting.com/public/id3dde595b4b1573/livetests/17237518

Seen on manual test on Kobiton cloud as well:
iPhone 5s (GSM) N51AP
iOS 9.3.4
UDID
1ff45400145003c1078b7dd6713695765a20ed97
Resolution 640 x 1136
portrait
![capture](https://user-images.githubusercontent.com/38503093/52683339-880c4b00-2f10-11e9-803d-e68aec628d3d.JPG)
Video is here: https://drive.google.com/open?id=1k8Pd_wQJtA2wRk4hPAuNuMslIik4jYV3
The kobiton source may not be viewable: https://portal.kobiton.com/sessions/613812

**Comment by sharifyounes** [comment]
I doubt it's an OS issue. More likely a Safari version issue.

**Comment by lgutro** [comment]
Using the new login page that uses angular,  I can still log in.  But the new GH page still has a problem. 

Here is video:  https://drive.google.com/file/d/1qCmAa6KeLVv-SSXbfEp6ZcSsvfjKnMnl/view?usp=drivesdk

I looked up that 11% of Apple smartphone users use < 11.0.
Also, I looked up the AngularJS bug database and I didn't see anything specific about iOS 10 and less.

**Comment by sharifyounes** [comment]
Is there any way to get the JS output? I assume there's some error there.

**Comment by lgutro** [comment]
how can I get the JS output?  I can log in and do things manually.

**Comment by lgutro** [comment]
@sharifyounes 
Is this what you want?  
[debug] [35m[MJSONWP][39m Calling AppiumDriver.click() with args: ["5170","d76287af-e3fa-43db-b634-0be7bf1c8434"]
[debug] [35m[XCUITest][39m Executing command 'click'
[debug] [35m[RemoteDebugger][39m Executing 'click' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Unable to collect garbage at this time
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Webkit response timeout: 5000
[debug] [35m[RemoteDebugger][39m Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":11,\"value\":{\"message\":\"Element is not currently visible and may not be manipulated\"}}"},"wasThrown":false},"id":36}'
[debug] [35m[RemoteDebugger][39m Found method 'Runtime.evaluate' for '36' message
[debug] [35m[MJSONWP][39m Matched JSONWP error code 11 to ElementNotVisibleError
[debug] [35m[MJSONWP][39m Encountered internal error running command: ElementNotVisibleError: Element is not currently visible and may not be manipulated
[debug] [35m[MJSONWP][39m     at errorFromMJSONWPStatusCode (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:786:12)
[debug] [35m[MJSONWP][39m     at WebKitRemoteDebugger.convertResult (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:656:6)
[debug] [35m[MJSONWP][39m     at WebKitRemoteDebugger.convertResult (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-remote-debugger.js:13:42)
[debug] [35m[MJSONWP][39m     at WebKitRemoteDebugger.execute$ (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/build/lib/remote-debugger.js:1539:54)
[debug] [35m[MJSONWP][39m     at tryCatch (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (/Applications/Kobiton.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[654358-842b01d0-40da-11e9-a1da-61b02b3988f7.zip](https://github.com/lgutro/hello-world/files/3018811/654358-842b01d0-40da-11e9-a1da-61b02b3988f7.zip)

**Comment by sharifyounes** [comment]
Hmm... I don't think so. Like if you go into the browser with "Inspect Element" and go to the Console, errors show up there. Is there something similar you can access use Kobiton?

**Comment by lgutro** [comment]
Please ignore that.
